### ISSUE TITLE
Delete button too close to save

### ISSUE THREAD

**Issue by aikruger** [ycnmhd/obsidian-lineage#44]
### What would you like to be added?

Move the delete icon to the bottom right of the card block or at least somewhere other than next to the save button

### Why is this feature needed?

I have deleted cards while intending to save

### Estimated usefulness for plugin users

Useful for some users

**Comment by ycnmhd** [comment]
You can adjust its position using this CSS snippet:
```css
button[aria-label="Delete"].lineage-floating-button {
	right: 30px;
}
```

If you use the plugin frequently, I'd recommend using the keyboard shortcut.
